maqueenStep.setBlackSensorValue(0)
maqueenStep.followLineForwardSteps(2, 80, 45)
maqueenStep.turn(MaqueenTurnSide.Left, MaqueenTurnAngle.Degree90, 70)
maqueenStep.followLineForwardSteps(1, 80, 45)
maqueenStep.turn(MaqueenTurnSide.Right, MaqueenTurnAngle.Degree180, 70)
